name: Build

on:
  # Call from other workflows
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      image_name:
        required: true
        type: string

permissions:
  # Only allow to read repo content
  contents: read

jobs:

  build_webapp:
    name: Build WebApp
    uses: ./.github/workflows/build_webapp.yml
    with:
      project_path: ${{ inputs.project_path }}
      artifact_name: ${{ inputs.artifact_name }}

  build_docker_image:
    name: Build Docker image
    uses: ./.github/workflows/build_docker_image.yml
    with:
      project_path: ${{ inputs.project_path }}
      image_name: ${{ inputs.image_name }}
      artifact_name: docker-${{ inputs.artifact_name }}
    
