name: Build Docker Image

on:
  # Call from other workflows
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

permissions:
  # Only allow to read repo content
  contents: read

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and save Docker image
        run: |
          docker build -f ${{ inputs.project_path }}/Dockerfile -t ${{ inputs.image_name }} .
          docker save -o ${{ inputs.image_name }}.tar ${{ inputs.image_name }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
            name: ${{ inputs.artifact_name }}
            path: ${{ inputs.image_name }}.tar

      

          