name: Build

on:
  # Call from other workflows
  workflow_call:

# Only allow to read repo content
permissions:
  contents: read

jobs:
  build:
    name: Build Web App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    