name: Deploy Web App

on:
  # Call from other workflows
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

# Only allow to read repo content
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Web App
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
   
    steps:

    # Download the build artifact
    - uses: actions/download-artifact@v1
      with:
        name: ${{ inputs.artifact_name }}
        path: ./${{ inputs.artifact_name }}

    # Azure Login using service principal
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: >-
            {
                "subscriptionId": "${{ vars.AZ_SUBSCRIPTION_ID }}",
                "tenantId": "${{ vars.AZ_TENANT_ID }}",
                "clientId": "${{ vars.AZ_SERVICE_PRINCIPAL_APP_ID }}",
                "clientSecret": "${{ secrets.AZ_SERVICE_PRINCIPAL_SECRET }}"
            }
    
    # Deploy to Azure Web App
    - name: 'Run Azure webapp deploy action using Azure Credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ vars.AZ_LINUX_WEB_APP_NAME }}
        slot-name: 'Production'
        package: ./${{ inputs.artifact_name }}
   
