name: Deploy Docker Image

on:
  # Call from other workflows
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      project_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      
permissions:
  # Only allow to read repo content
  contents: read
  # Allow to write tokens for Azure Login OIDC
  id-token: write

jobs:
  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
   
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Azure Login using service principal
    - name: Azure login
      uses: azure/login@v2
      with:
        subscription-id: ${{ vars.AZ_SUBSCRIPTION_ID }}
        tenant-id: ${{ vars.AZ_TENANT_ID }}
        client-id: ${{ vars.AZ_SERVICE_PRINCIPAL_APP_ID }}

    # Docker ACR Login
    - name: Login to ACR via OIDC
      run: az acr login --name ${{ vars.AZ_CONTAINER_REGISTRY_NAME }}
    
    # Build and push docker image to ACR
    - run: |
        docker build -f ${{ inputs.project_path }}/Dockerfile -t  ${{ vars.AZ_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ inputs.image_name }}:${{ github.sha }} .
        docker push ${{ vars.AZ_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ inputs.image_name }}:${{ github.sha }} 
