name: Deploy Linux Web App

on:
  # Call from other workflows
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

permissions:
  # Only allow to read repo content
  contents: read
  # Allow to write tokens for Azure Login OIDC
  id-token: write

jobs:
  deploy:
    name: Deploy Web App
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
   
    steps:

    - name: Download artifact from build job
      uses: actions/download-artifact@v1
      with:
        name: ${{ inputs.artifact_name }}
        path: ./${{ inputs.artifact_name }}

    # Azure Login using service principal with OIDC
    # https://github.com/marketplace/actions/azure-login#login-with-openid-connect-oidc-recommended
    - name: Azure login
      uses: azure/login@v2
      with:
        subscription-id: ${{ vars.AZ_SUBSCRIPTION_ID }}
        tenant-id: ${{ vars.AZ_TENANT_ID }}
        client-id: ${{ vars.AZ_SERVICE_PRINCIPAL_APP_ID }}
    
    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ vars.AZ_LINUX_WEB_APP_NAME }}
        package: ./${{ inputs.artifact_name }}
   
    - name: Smoke Test
      run: |
        status=`curl --silent --head -X GET --max-time 300 https://${{ vars.AZ_LINUX_WEB_APP_NAME }}.azurewebsites.net | head --lines 1 | cut --fields 2 --delimiter ' '`
        if [[ $status -ne 200 ]]
        then
            echo Smoke test failed with status code $status.
            exit -1
        else
            echo Smoke test successful with status code $status.
            exit 0
        fi
