name: Main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy_default:
    name: Deploy on Default Environment
    uses: ./.github/workflows/deploy_terraform.yml
    with:
      environment: default

  deploy_alternate:
    name: Deploy on Alternate Environment
    uses: ./.github/workflows/deploy_terraform.yml
    with:
        environment: alternate