name: Main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy_default:
    uses: ./.github/workflows/deploy_terraform.yml@main
    with:
      environment: default