name: Main

on:
  # Run on push to Main
  push:
    branches: [ "main" ]
  # Run manually
  workflow_dispatch:

# Only allow to read repo content
permissions:
    contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  deploy_default:
    name: Deploy on Default Environment
    uses: ./.github/workflows/deploy_infrastructure.yml
    with:
      environment: default
    secrets: inherit