name: Main

on:
  # Run on push to Main
  push:
    branches: [ "main" ]
  # Run manually
  workflow_dispatch:

# Only allow to read repo content
permissions:
    contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      project_path: './src/AspNetCore.Examples.TerraformAzure.Api'
      artifact_name: 'web-app'

  deploy_default:
    name: Deploy on Default Environment
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: default
      artifact_name: 'web-app'
    secrets: inherit