name: Default

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: default

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    env:
        TF_VAR_azurerm_subscription_id: ${{ vars.AZ_SUBSCRIPTION_ID }}
        TF_VAR_azurerm_tenant_id: ${{ vars.AZ_TENANT_ID }}
        TF_VAR_azurerm_client_id: ${{ vars.AZ_SERVICE_PRINCIPAL_APP_ID }}
        TF_VAR_azurerm_client_secret: ${{ secrets.AZ_SERVICE_PRINCIPAL_SECRET }}
        TF_VAR_resource_group_name: ${{ vars.AZ_RESOURCE_GROUP_NAME }}
        TF_VAR_resource_group_location: ${{ vars.AZ_RESOURCE_GROUP_LOCATION }}
        TF_VAR_storage_account_name: ${{ vars.AZ_STORAGE_ACCOUNT_NAME }}

    steps:

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest compatible version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: ~>1.5

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: ./terraform
      run: >- 
        terraform init 
        -backend-config="subscription_id=${{ vars.AZ_SUBSCRIPTION_ID }}"
        -backend-config="tenant_id=${{ vars.AZ_TENANT_ID }}"
        -backend-config="client_id=${{ vars.AZ_SERVICE_PRINCIPAL_APP_ID }}"
        -backend-config="client_secret=${{ secrets.AZ_SERVICE_PRINCIPAL_SECRET }}"
        -backend-config="resource_group_name=${{ vars.AZ_RESOURCE_GROUP_NAME }}"
        -backend-config="storage_account_name=${{ vars.AZ_STORAGE_ACCOUNT_NAME }}"

